trigger:
- $(branchName)

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    response=$(curl -i -X POST \
    -H "Authorization: token $(GITHUB_TOKEN)" \
    -H "Accept: application/vnd.github.v3+json" \
    https://api.github.com/repos/Bal-os/CurrencyExchangeService/actions/workflows/$(branchName)_currencyexchangeservice.yml/dispatches \
    -d '{"ref":"$(branchName)"}')
    echo "Response: $response"
  displayName: 'Trigger GitHub Action'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    branchName: $(branchName)
